module.exports = {
  tableName: 'companies',
  entity: 'company',
  primaryKey: 'id',
  columns: [
    'id',
    'removed',
    'enabled',
    'name',
    'industry',
    'website',
    'email',
    'phone',
    'address',
    'country',
    'notes',
    'created_by',
    'assigned',
    'created',
    'updated',
  ],
  filterableFields: ['enabled', 'industry', 'country', 'created_by', 'assigned'],
  searchableFields: ['name', 'email', 'phone', 'address', 'website'],
  sortableFields: ['name', 'created', 'updated', 'enabled'],
  defaultSort: 'enabled',
};
