module.exports = {
  tableName: 'leads',
  entity: 'lead',
  primaryKey: 'id',
  columns: [
    'id',
    'removed',
    'enabled',
    'name',
    'email',
    'phone',
    'company_name',
    'company_id',
    'status',
    'source',
    'notes',
    'converted_to_client_id',
    'converted_at',
    'created_by',
    'assigned',
    'created',
    'updated',
  ],
  filterableFields: ['status', 'source', 'enabled', 'company_id', 'created_by', 'assigned', 'converted_to_client_id'],
  searchableFields: ['name', 'email', 'phone', 'company_name'],
  sortableFields: ['name', 'status', 'created', 'updated', 'enabled'],
  defaultSort: 'created',
};
