module.exports = {
  tableName: 'offers',
  entity: 'offer',
  primaryKey: 'id',
  columns: [
    'id',
    'removed',
    'created_by',
    'number',
    'year',
    'content',
    'date',
    'expired_date',
    'client_id',
    'tax_rate',
    'sub_total',
    'tax_total',
    'total',
    'currency',
    'discount',
    'notes',
    'status',
    'pdf',
    'updated',
    'created',
  ],
  filterableFields: ['status', 'client_id', 'created_by', 'year'],
  searchableFields: ['number', 'notes', 'content'],
  sortableFields: ['number', 'date', 'expired_date', 'total', 'status', 'created', 'updated'],
  defaultSort: 'created',
};
