module.exports = {
  tableName: 'orders',
  entity: 'order',
  primaryKey: 'id',
  columns: [
    'id',
    'removed',
    'created_by',
    'number',
    'year',
    'date',
    'client_id',
    'tax_rate',
    'sub_total',
    'tax_total',
    'total',
    'currency',
    'discount',
    'credit',
    'notes',
    'status',
    'payment_status',
    'pdf',
    'updated',
    'created',
  ],
  filterableFields: ['status', 'payment_status', 'client_id', 'created_by', 'year'],
  searchableFields: ['number', 'notes'],
  sortableFields: ['number', 'date', 'total', 'status', 'payment_status', 'created', 'updated'],
  defaultSort: 'created',
};
