module.exports = {
  tableName: 'payments',
  entity: 'payment',
  primaryKey: 'id',
  columns: [
    'id',
    'removed',
    'created_by',
    'number',
    'client_id',
    'invoice_id',
    'date',
    'amount',
    'currency',
    'ref',
    'description',
    'pdf',
    'updated',
    'created',
  ],
  filterableFields: ['client_id', 'invoice_id', 'created_by'],
  searchableFields: ['number', 'ref', 'description'],
  sortableFields: ['number', 'date', 'amount', 'created', 'updated'],
  defaultSort: 'created',
};
