module.exports = {
  tableName: 'products',
  entity: 'product',
  primaryKey: 'id',
  columns: [
    'id',
    'removed',
    'enabled',
    'name',
    'description',
    'sku',
    'category_id',
    'price',
    'quantity',
    'unit',
    'tax_rate',
    'created_by',
    'created',
    'updated',
  ],
  filterableFields: ['enabled', 'category_id', 'created_by'],
  searchableFields: ['name', 'description', 'sku'],
  sortableFields: ['name', 'price', 'quantity', 'created', 'updated', 'enabled'],
  defaultSort: 'enabled',
};
